# Logging
elasticsearch:
  image: elasticsearch:2
  ports:
    - "9200"
    - "9300"
  volumes:
    - /opt/foursball/data:/usr/share/elasticsearch/data

kibana:
  image: kibana:4
  ports:
    - "5601:5601"
  links:
    - elasticsearch

fluentd:
  build: fluentd/
  ports:
    - "24224:24224"
  links:
    - elasticsearch
