# Apps
api:
  image: foursball/foursball-api:latest
  container_name: api
  ports:
    - "8000:80"
  labels:
    - "traefik.backend=api"
  environment:
    - SERVER_URL=http://api.localhost
    - MYSQL_HOST=mysql
    - FLUENTD_HOST=fluentd
  links:
    - mysql
    - fluentd
  env_file: .env
  restart: always

mysql:
  image: mysql:latest
  ports:
    - "3306:3306"
  environment:
    - MYSQL_DATABASE=sails
    - MYSQL_USER=sails
    - MYSQL_PASSWORD=sails
    - MYSQL_RANDOM_ROOT_PASSWORD=true
  restart: always

# Logging
elasticsearch:
  image: elasticsearch:2
  ports:
    - "9200"
    - "9300"
  labels:
    - "traefik.enable=false"
  volumes:
    - /opt/foursball/data:/usr/share/elasticsearch/data
  log_driver: none
  restart: always

kibana:
  image: kibana:4
  container_name: log
  ports:
    - "5601:5601"
  labels:
    - "traefik.backend=kibana"
  links:
    - elasticsearch
  restart: always

fluentd:
  build: fluentd/
  ports:
    - "24224:24224"
  labels:
    - "traefik.enable=false"
  links:
    - elasticsearch
  restart: always

# Proxy
traefik:
  image: traefik
  command: --web --docker --docker.domain=localhost --logLevel=DEBUG
  ports:
    - "80:80"
    - "8080:8080"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  restart: always

# Docker Management
portainer:
  image: portainer/portainer
  container_name: portainer
  ports:
    - "9000:9000"
  labels:
    - "traefik.backend=portainer"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  restart: always
