# UI
ui:
  image: foursball/foosball:sails-api
  container_name: ui
  ports:
    - "4200:4200"
  environment:
    - API_URL=http://app.localhost
  restart: always

# API
api:
  image: foursball/foursball-api:latest
  container_name: app
  mem_limit: 250m
  environment:
    - SERVER_URL=http://app.localhost
    - MYSQL_HOST=mysql
    - DATA_RESTORE=true
    - PROXY_ENABLED=true
    - PROXY_URL=http://<local-ip>:4200
    - FLUENTD_HOST=fluentd
#  volumes:
#    - /path/to/pwd/restore:/usr/src/app/restore
  links:
    - mysql
    - fluentd
  env_file: .env
  restart: always

mysql:
  image: mysql:latest
  container_name: mysql
  ports:
    - "3306:3306"
  labels:
    - "traefik.enable=false"
  environment:
    - MYSQL_DATABASE=sails
    - MYSQL_USER=sails
    - MYSQL_PASSWORD=sails
    - MYSQL_RANDOM_ROOT_PASSWORD=true
#  volumes:
#    - /path/to/pwd/mysql:/var/lib/mysql
  restart: always

# Logging
elasticsearch:
  image: elasticsearch:2
  container_name: elasticsearch
  ports:
    - "9200"
    - "9300"
  labels:
    - "traefik.enable=false"
#  volumes:
#    - /path/to/pwd/elasticsearch:/usr/share/elasticsearch/data
  log_driver: none
  restart: always

kibana:
  image: kibana:4
  container_name: log
  mem_limit: 100m
  links:
    - elasticsearch
  restart: always

fluentd:
  build: fluentd/
  container_name: fluentd
  mem_limit: 100m
  ports:
    - "24224:24224"
  labels:
    - "traefik.enable=false"
  links:
    - elasticsearch
  restart: always

# Proxy
traefik:
  image: traefik
  container_name: traefik
  mem_limit: 50m
  command: --web --docker --docker.domain=localhost --logLevel=DEBUG
  ports:
    - "80:80"
    - "8080:8080"
    - "443:443"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
#    - /path/to/pwd/traefik.toml:/traefik.toml
#    - /path/to/pwd/acme.json:/acme.json
  restart: always

# Docker Management
portainer:
  image: portainer/portainer
  container_name: portainer
  mem_limit: 50m
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
#    - /path/to/pwd/portainer:/data
  restart: always
