# Logging
elasticsearch:
  image: elasticsearch:2
  ports:
    - "9200"
    - "9300"
  labels:
    - "traefik.enable=false"
  volumes:
    - /opt/foursball/data:/usr/share/elasticsearch/data

kibana:
  image: kibana:4
  container_name: log
  ports:
    - "5601:5601"
  labels:
    - "traefik.backend=kibana"
  links:
    - elasticsearch

fluentd:
  build: fluentd/
  ports:
    - "24224:24224"
  labels:
    - "traefik.enable=false"
  links:
    - elasticsearch

# Proxy
traefik:
  image: traefik
  command: --web --docker --docker.domain=localhost --logLevel=DEBUG
  ports:
    - "80:80"
    - "8080:8080"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
