defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]
[acme]
email = "brian@foursball.com"
entryPoint = "https"
storageFile = "acme.json"
onDemand = true
[[acme.domains]]
  main = "app.foursball.com"
